export const CATEGORIES = [
  { id: 'ia', label: 'Inteligencia Artificial', color: 'var(--tag-ai)', textColor: 'var(--tag-ai-text)' },
  { id: 'web', label: 'Desarrollo Web', color: 'var(--tag-tech)', textColor: 'var(--tag-tech-text)' },
  { id: 'data', label: 'Ciencia de Datos', color: 'var(--tag-data)', textColor: 'var(--tag-data-text)' },
  { id: 'env', label: 'Medio Ambiente', color: 'var(--tag-env)', textColor: 'var(--tag-env-text)' },
  { id: 'tcnp', label: 'TCNP', color: '#fce7f3', textColor: '#be185d' },
  { id: 'iot', label: 'IoT', color: '#e0f2fe', textColor: '#0369a1' },
  { id: 'robotica', label: 'Robótica', color: '#fef3c7', textColor: '#b45309' },
  { id: 'blockchain', label: 'Blockchain', color: '#f0fdf4', textColor: '#15803d' },
]

export const POPULAR_TAGS = ['Inteligencia Artificial', 'TCNP', 'Medio Ambiente', 'Machine Learning', 'IoT', 'Blockchain']

export const MOCK_PROJECTS = [
  {
    id: 1,
    title: 'Entrenamiento mediante algoritmos de machine learning y deep learning.',
    category: 'Inteligencia Artificial',
    categoryId: 'ia',
    author: 'Carlos M.',
    authorId: 1,
    university: 'EPN',
    image: null,
    likes: 13,
    views: 15,
    comments: 7,
    featured: true,
    createdAt: '2026-01-15',
    description: 'Proyecto de investigación enfocado en el desarrollo de modelos de ML para predicción de datos universitarios.',
    tags: ['Python', 'TensorFlow', 'Deep Learning'],
  },
  {
    id: 2,
    title: 'Sistema de monitoreo ambiental con sensores IoT en tiempo real',
    category: 'Medio Ambiente',
    categoryId: 'env',
    author: 'María P.',
    authorId: 2,
    university: 'ESPE',
    image: null,
    likes: 28,
    views: 45,
    comments: 12,
    featured: true,
    createdAt: '2026-02-03',
    description: 'Red de sensores IoT para monitoreo de calidad del aire en zonas urbanas.',
    tags: ['Arduino', 'IoT', 'React'],
  },
  {
    id: 3,
    title: 'Plataforma de detección de enfermedades en cultivos usando visión artificial',
    category: 'Inteligencia Artificial',
    categoryId: 'ia',
    author: 'Diego S.',
    authorId: 3,
    university: 'UCE',
    image: null,
    likes: 41,
    views: 88,
    comments: 19,
    featured: true,
    createdAt: '2026-01-28',
    description: 'Uso de redes neuronales convolucionales para identificar enfermedades en plantas agrícolas.',
    tags: ['PyTorch', 'OpenCV', 'FastAPI'],
  },
  {
    id: 4,
    title: 'Chatbot universitario para orientación académica con NLP',
    category: 'Inteligencia Artificial',
    categoryId: 'ia',
    author: 'Sofía L.',
    authorId: 4,
    university: 'PUCE',
    image: null,
    likes: 22,
    views: 56,
    comments: 8,
    featured: true,
    createdAt: '2026-03-01',
    description: 'Asistente conversacional con procesamiento de lenguaje natural para guiar a estudiantes.',
    tags: ['NLP', 'Python', 'Rasa'],
  },
  {
    id: 5,
    title: 'Análisis de tráfico vehicular con drones y Computer Vision',
    category: 'Ciencia de Datos',
    categoryId: 'data',
    author: 'Andrés T.',
    authorId: 5,
    university: 'UDLA',
    image: null,
    likes: 35,
    views: 72,
    comments: 14,
    featured: false,
    createdAt: '2026-02-14',
    description: 'Sistema de visión artificial montado en drones para análisis de flujo vehicular urbano.',
    tags: ['YOLO', 'Python', 'Drone'],
  },
  {
    id: 6,
    title: 'Red blockchain para validación de certificados académicos',
    category: 'TCNP',
    categoryId: 'tcnp',
    author: 'Valeria R.',
    authorId: 6,
    university: 'UTE',
    image: null,
    likes: 18,
    views: 39,
    comments: 6,
    featured: false,
    createdAt: '2026-03-10',
    description: 'Plataforma descentralizada para emisión y verificación de títulos y certificados universitarios.',
    tags: ['Ethereum', 'Solidity', 'Web3'],
  },
  {
    id: 7,
    title: 'App móvil para gestión de residuos sólidos urbanos',
    category: 'Medio Ambiente',
    categoryId: 'env',
    author: 'Roberto F.',
    authorId: 7,
    university: 'UIDE',
    image: null,
    likes: 29,
    views: 61,
    comments: 11,
    featured: false,
    createdAt: '2026-01-20',
    description: 'Aplicación móvil que conecta ciudadanos con operadores de recolección de residuos.',
    tags: ['React Native', 'Firebase', 'Maps API'],
  },
  {
    id: 8,
    title: 'Brazo robótico asistido por IA para personas con discapacidad',
    category: 'Robótica',
    categoryId: 'robotica',
    author: 'Camila V.',
    authorId: 8,
    university: 'EPN',
    image: null,
    likes: 67,
    views: 134,
    comments: 31,
    featured: false,
    createdAt: '2026-02-28',
    description: 'Prótesis robótica inteligente controlada por señales electromiográficas.',
    tags: ['Arduino', 'Python', 'EMG'],
  },
]

export const getCategoryStyle = (categoryId) => {
  const cat = CATEGORIES.find(c => c.id === categoryId)
  return cat
    ? { background: cat.color, color: cat.textColor }
    : { background: 'var(--bg-subtle)', color: 'var(--text-secondary)' }
}